/**
 * Decision Tree Classification With Uncertain Data (UDT)
 * Copyright (C) 2009, The Database Group, 
 * Department of Computer Science, The University of Hong Kong
 * 
 * This file is part of UDT.
 *
 * UDT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * UDT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.decisiontree.datagen;

/**
 * 
 * DataCleaner (Interface) - Cleans the generated data files.
 *
 * @author Smith Tsang
 * @since 0.8
 *
 */
public interface DataCleaner {
	/**
	 * Clear a set of generate data generated by a given input
	 * @param input the name of the data
	 */
	public void cleanGeneratedData(String input);
	
	/**
	 * Clear a set of generate data and test data generated by a given training and testing
	 * @param training the name of training data
	 * @param testing the name of the testing data
	 */
	public void cleanGeneratedDataWithTest(String training, String testing);
}
